apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-helloworld-ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: helloworld
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - hello
