apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data: 
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
    - "recording_rules.yml"

    scrape_configs:
      # Scrape prometheus
    - job_name: prometheus
      static_configs:
      - targets: ['localhost:9090']

      # Scrape Kubernetes nodes (kubelet metrics)
    - job_name: kubernetes-nodes'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

    # Scrape node cAdvisor for container/system metrics
    - job_name: 'kubernetes-cadvisor'
      kubernetes_sd_configs:
        - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
  recording_rules.yml: |
    groups:
    - name: node_metrics
      interval: 30s
      rules:
      # Node CPU usage percentage
      - record: homelab:node_cpu_usage_percent
        expr: rate(container_cpu_usage_seconds_total{id="/"}[5m]) * 100

      # Node memory usage in bytes  
      - record: homelab:node_memory_usage_bytes
        expr: container_memory_usage_bytes{id="/"}

      # Node memory usage percentage
      - record: homelab:node_memory_usage_percent
        expr: (container_memory_usage_bytes{id="/"} / container_spec_memory_limit_bytes{id="/"}) * 100

      # Node memory available in GB (easier to read)
      - record: homelab:node_memory_usage_gb
        expr: container_memory_usage_bytes{id="/"} / 1024 / 1024 / 1024
