# https://github.com/Mic92/sops-nix
keys:
  - &gustaf_mbp age1j0kun6sgqunj0ll7dzsrl7dv8l8h423z3e7z845we7kayq96nshqwn8fgd
  - &homelab1 age1ap55tggyg26qsd44vw30ayzj792zgsz98jna7zhjcuy9amszne7sy2ts6z
  - &homelab2 age17p0h8gpsxhmq7p2nk7r56rmt0y7xv88jlhm304guwfc3250z5p9qpjvm2g
  - &homelab3 age17vy29ayvjxk6rs66rc5wcluy9x09y3y8n75psmuutzt6mel675hs6ktf5w
creation_rules:
  - path_regex: .secret.env
    key_groups:
    - age:
      - *gustaf_mbp
      - *homelab1
      - *homelab2
      - *homelab3
  - path_regex: certs/.*.key
    key_groups:
    - age:
      - *gustaf_mbp
      - *homelab1
      - *homelab2
      - *homelab3
  - path_regex: kubernetes/tls.yaml
    encrypted_regex: '^(data|stringData)$'
    key_groups:
    - age:
      - *gustaf_mbp
      - *homelab1
      - *homelab2
      - *homelab3
  - path_regex: kubernetes/secrets.yaml
    encrypted_regex: '^(data|stringData)$'
    key_groups:
    - age:
      - *gustaf_mbp
      - *homelab1
      - *homelab2
      - *homelab3
  - path_regex: secrets.yaml
    key_groups:
    - age:
      - *gustaf_mbp
      - *homelab1
      - *homelab2
      - *homelab3
