apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tls.yaml
- secrets.yaml
- ../helloworld/deploy/
- ../homeassistant/deploy/
- ../postgres/deploy/
- ../prometheus/deploy/
- ../tailscale/deploy/
