apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 5m0s
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./services/deploy/
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
