apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ../../services/deploy/
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
