apiVersion: v1
kind: Secret
metadata:
    name: homelab-secrets
    namespace: default
type: Opaque
stringData:
    HELLOWORLD: ENC[AES256_GCM,data:y+4toErzjmaoqGs5XO3l2wevig3ndw==,iv:CFD69JUcqCxWr7qx4K/qHOlHslmOYbwxkvkKc21JQNA=,tag:XyI9TqdoLiEGAf5i+CjT/w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:CrzlyvmzXQ==,iv:lmFwq74oU0QnvxxHveqBYKMsXb2m1Atc6fSDsxSzmTI=,tag:smjBtl2YUdv4dkZNZ/z64w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:TEw8wLoD/W4=,iv:SYdUo/aTybx0ds6PkEzjbHwIKpJ6VNXWQc7FQpXkoFk=,tag:nlE8S2CVoFdR92VExHEtXg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZSETfOBeg+Keo4bLBx45Y+fS4UrsQcI2WsWDn+F1De2DfZCwlgibYDyvZBF7O7ibQPTsobDnUxDM/vjc6c4z0Q==,iv:QvNNOUz4uW67esep2m5FM1ahFgCrsApK+SuQMG1glPM=,tag:HViL0L87FBGcgbvewXZoiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0kun6sgqunj0ll7dzsrl7dv8l8h423z3e7z845we7kayq96nshqwn8fgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Tk81L25JT3dKUHVEN3Jp
            TFFMTFh6TmdTaUpWMkh4YkNqOWRTT2xjZ0dZCm10ZmdQRTc4MWhBMlZ0eVhnNysy
            L24yNXRTZ0pLTFc5NkNEZzY3S1Urc0EKLS0tIGRoYXZZYkE0QTdEVU5lYnJqekJP
            elhXVzVNMVR4bm9pZ3cxYjlQU2FmWjQKWOo+8zvYe+7HM0DCE57mK3s8kZZAfYlw
            BDcYCAy1wSgANlS/QO2rAmmZ+GWestpjwIMKPXkjX4D3lI86PsK17w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ap55tggyg26qsd44vw30ayzj792zgsz98jna7zhjcuy9amszne7sy2ts6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcEU4dHE2SUlHUlNzU1ht
            bkIvMkpSL1VhbTFZN2xCMzlKZnhJZFJ1aVNNCkt5UjRHTWJleWNxaGlHZTcvZmhN
            MFMwS09NMWlpdjBvU0FJYmZZN1pYek0KLS0tIE93WVdZL3JnbFFsT2R4bm1PRjBQ
            aldKd0RsdWNDVlhmakxtMnpNWmlwVmMKcdn+TufATo8+E/UXog07W0L5coxLliDB
            1HYtiB0sgpY7xUL/+Rf5xnGGVNTyYzlKlqcuZeUGFlJX/cOKlC9bFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17p0h8gpsxhmq7p2nk7r56rmt0y7xv88jlhm304guwfc3250z5p9qpjvm2g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQzZzRGtuSVM1RkxlTVBU
            MjZtM1owVklrWTc3VXJ3TngzdjlpV05QcGk0CmZWa0lrOTlwaHJkNURjL0JsbmZq
            Z1hnTzVJajBzYnIyUDQyK3JCWlNiZ1EKLS0tIE15YVhhZUd3Rndwanc1SjZsdjU1
            ZzRzQ0dDci9hc2hTT1dlc1k5VmxiSlkKZBq2lkdh+kQYr8lmHUsozpDw0bUteNtU
            3K16O2Hm1+8XVLy3jFZNz94sJeyWq33EmCQMBL9+X03Ru8IA3WOhWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17vy29ayvjxk6rs66rc5wcluy9x09y3y8n75psmuutzt6mel675hs6ktf5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MTc3c2dKdk5JSFcvb2VY
            bkY5b2JOSWtjSFJXZHExYitJeTNxRUVURWxnCmJZSlJDakQ5Y1RGK0k1dXFwQkNn
            R3d1Smc2Rjk4NTkyaWFRNmZ2S1BIcEUKLS0tIDNnbFpGZkFvUDUxY0dpN0hOTVZw
            VlpJbWE5K0lZMmlyYW9QaWkwNDVrSEEKmE++hU6AVNEi8w0XNndc7Xtr3BA0ZDjL
            rIZgdQ1s21Jmbi5bNJQjIgoKFZhOdpUSuYDJQ22Uxv6pmPcPLScI1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-26T14:05:30Z"
    mac: ENC[AES256_GCM,data:CnGC1+iwZYr1S8K3qIaMFYpmWunqhcyRCdwdIJZ0xcopDhunPO9sba9iaIWuyyx/BUj7MmrXJHdPSdQpRjhErw7QHwqVITjSezvgULb4xSMJtT+KnrmRXKmFxdrHray/tua4aEsExstUb7tzgy91rkH4NRPAV8hLMN0E231lP3Q=,iv:X2MIPDhpBFjBpoifYym75HYdZg+lSlChw+xag/8Xp10=,tag:AimFHIrWgmvi95IVE3f+4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
