apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: default
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:2025.6.0b3
        ports:
        - containerPort: 8123
        env:
        - name: TZ
          value: "Europe/Stockholm"
        volumeMounts:
        - name: homeassistant-config
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          privileged: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
      nodeSelector:
        kubernetes.io/hostname: homelab1
      volumes:
      - name: homeassistant-config
        persistentVolumeClaim:
          claimName: homeassistant-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
