apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels: 
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17.5-alpine3.21
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
              secretKeyRef:
                name: homelab-secrets
                key: postgres_db
        - name: POSTGRES_USER
          valueFrom:
              secretKeyRef:
                name: homelab-secrets
                key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                name: homelab-secrets
                key: postgres_password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
            - -d
            - homelab
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
            - -d
            - homelab
          initialDelaySeconds: 5
          periodSeconds: 5
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

